### PR TITLE
Add gz alias

### PR DESCRIPTION
**Pull request by chapulina**
* https://github.com/gazebo-tooling/release-tools/issues/788

Test Focal amd64 build targeted at the pre-release repo: [Build Status](https://build.osrfoundation.org/job/ign-cmake2-debbuilder/1656/)

### CODE REVIEW

**Comment by j-rivero** [comment]
Your approach here is to add the new name as an alias for the old package. As Debian recommends in https://wiki.debian.org/RenamingPackages we can do the opposite, change the package name and add the old package as the "alias" (transitional package) for it.

**Comment by chapulina** [comment]
Thanks. I'll try to follow the pattern we did for Garden then 🤞🏽 

* https://github.com/gazebo-release/gz-cmake3-release/pull/6

**Comment by chapulina** [comment]
Before going all in and renaming the package, here's an attempt of making the `gz-` package just look like a regular package, no renaming or aliasing or anything:

[Build Status](https://build.osrfoundation.org/job/ign-cmake2-debbuilder/1657/)

I'm a bit worried about being too intrusive with these stable packages. I'd be more comfortable doing the least intrusive action (i.e. just adding new `gz-` packages without changing any of the `ignition-` ones) to be safe. Not sure if that's disallowed by debian best practices.

**Comment by chapulina** [comment]
[Build Status](https://build.osrfoundation.org/job/ign-cmake2-debbuilder/1658/)

**Comment by chapulina** [comment]
[Build Status](https://build.osrfoundation.org/job/ign-cmake2-debbuilder/1659/)

**Comment by chapulina** [comment]
[Build Status](https://build.osrfoundation.org/job/ign-cmake2-debbuilder/1660/)

**Comment by chapulina** [comment]
[Build Status](https://build.osrfoundation.org/job/ign-cmake2-debbuilder/1661/)

**Comment by chapulina** [comment]
[Build Status](https://build.osrfoundation.org/job/ign-cmake2-debbuilder/1662/)

**Comment by chapulina** [comment]
[Build Status](https://build.osrfoundation.org/job/ign-cmake2-debbuilder/1663/)

**Comment by chapulina** [comment]
[Build Status](https://build.osrfoundation.org/job/ign-cmake2-debbuilder/1668/)

**Comment by chapulina** [comment]
It works! Installing in a system that already has `ignition`:

```
chapulina@pasokinho:/media/chapulina/TERA/code/citadel-release-repos/gz-cmake2-release$ sudo apt install libgz-cmake2-dev                                 
Reading package lists... Done                                                                                                                                                   
Building dependency tree                                                                                                                                                        
Reading state information... Done                                                                                                                                               
The following NEW packages will be installed:                                                                                                                                   
  libgz-cmake2-dev                                                                                                                                                              
0 upgraded, 1 newly installed, 0 to remove and 547 not upgraded.                                                                                                                
Need to get 2,028 B of archives.                                                                                                                                                
After this operation, 8,192 B of additional disk space will be used. 
Get:1 http://packages.osrfoundation.org/gazebo/ubuntu-prerelease focal/main amd64 libgz-cmake2-dev all 2.14.0-1~focal [2,028 B]
Fetched 2,028 B in 0s (5,617 B/s)                                                                                                                                               
Selecting previously unselected package libgz-cmake2-dev.               
(Reading database ... 510201 files and directories currently installed.)                                                                                                        
Preparing to unpack .../libgz-cmake2-dev_2.14.0-1~focal_all.deb ...  
Unpacking libgz-cmake2-dev (2.14.0-1~focal) ...                          
Setting up libgz-cmake2-dev (2.14.0-1~focal) ...
```

And if it doesn't have `ignition` yet:

```
chapulina@pasokinho:/media/chapulina/TERA/code/citadel-release-repos/gz-cmake2-release$ sudo apt install libgz-cmake2-dev 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libignition-cmake2-dev
The following NEW packages will be installed:
  libgz-cmake2-dev libignition-cmake2-dev
0 upgraded, 2 newly installed, 0 to remove and 542 not upgraded.
Need to get 4,224 B of archives.
After this operation, 16.4 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://packages.osrfoundation.org/gazebo/ubuntu-prerelease focal/main amd64 libignition-cmake2-dev amd64 2.14.0-1~focal [2,196 B]
Get:2 http://packages.osrfoundation.org/gazebo/ubuntu-prerelease focal/main amd64 libgz-cmake2-dev all 2.14.0-1~focal [2,028 B]
Fetched 4,224 B in 0s (17.2 kB/s)           
Selecting previously unselected package libignition-cmake2-dev:amd64.
(Reading database ... 498407 files and directories currently installed.)
Preparing to unpack .../libignition-cmake2-dev_2.14.0-1~focal_amd64.deb ...
Unpacking libignition-cmake2-dev:amd64 (2.14.0-1~focal) ...
Selecting previously unselected package libgz-cmake2-dev.
Preparing to unpack .../libgz-cmake2-dev_2.14.0-1~focal_all.deb ...
Unpacking libgz-cmake2-dev (2.14.0-1~focal) ...
Setting up libignition-cmake2-dev:amd64 (2.14.0-1~focal) ...
Setting up libgz-cmake2-dev (2.14.0-1~focal) ...
```

**Review by j-rivero — COMMENTED** [review]
Looks great to me. Great work!

**Review by j-rivero — APPROVED** [review]

**Pull request merged**
